### ISSUE TITLE
Practica 3 Visual Studio Interfaz Grafica Menu

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-tadp-isag#1]
[Practica.3.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-tadp-isag/files/8175474/Practica.3.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by Yareli-Perez** [comment]
calificación = 92 = 18.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
